// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksAPI.Models;

namespace ParksAPI.Migrations
{
    [DbContext(typeof(ParksAPIContext))]
    [Migration("20220911023413_Pagination")]
    partial class Pagination
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<string>("TypeOfPark")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Location = "Maine",
                            ParkName = "Acadia National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            Location = "American Samoa Territory",
                            ParkName = "American Samoa National Park	",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            Location = "Utah",
                            ParkName = "Arches National Park	",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 4,
                            Location = "South Dakota",
                            ParkName = "Badlands National Park ",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 5,
                            Location = "Texas",
                            ParkName = "Big Bend National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 6,
                            Location = "Florida",
                            ParkName = "Biscayne National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 7,
                            Location = "Colorado",
                            ParkName = "Black Canyon of the Gunnison National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 8,
                            Location = "Utah",
                            ParkName = "Bryce Canyon National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 9,
                            Location = "Utah",
                            ParkName = "Canyonlands National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 10,
                            Location = "Utah",
                            ParkName = "Capitol Reef National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 11,
                            Location = "New Mexico",
                            ParkName = "Carlsbad Caverns National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 12,
                            Location = "California",
                            ParkName = "Channel Islands National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 13,
                            Location = "South Carolina",
                            ParkName = "Congaree National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 14,
                            Location = "Oregon",
                            ParkName = "Crater Lake National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 15,
                            Location = "Ohio",
                            ParkName = "Cuyahoga Valley National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 16,
                            Location = "California and Nevada",
                            ParkName = "Death Valley National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 17,
                            Location = "Alaska",
                            ParkName = "Denali National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 18,
                            Location = "Florida",
                            ParkName = "Dry Tortugas National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 19,
                            Location = "Florida",
                            ParkName = "Everglades National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 20,
                            Location = "Alaska",
                            ParkName = "Gates of the Arctic National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 21,
                            Location = "Missouri",
                            ParkName = "Gateway Arch National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 22,
                            Location = "Montana",
                            ParkName = "Glacier National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 23,
                            Location = "Alaska",
                            ParkName = "Glacier Bay National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 24,
                            Location = "Arizona",
                            ParkName = "Grand Canyon National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 25,
                            Location = "Wyoming",
                            ParkName = "Grand Teton National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 26,
                            Location = "Nevada",
                            ParkName = "Great Basin National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 27,
                            Location = "Colorado",
                            ParkName = "Great Sand Dunes National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 28,
                            Location = "North Carolina and Tennessee",
                            ParkName = "Great Smoky Mountains National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 29,
                            Location = "Texas",
                            ParkName = "Guadalupe Mountains National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 30,
                            Location = "Hawaii",
                            ParkName = "Haleakala National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 31,
                            Location = "Hawaii",
                            ParkName = "Hawaii Volcanoes National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 32,
                            Location = "Arkansas",
                            ParkName = "Hot Springs National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 33,
                            Location = "Indiana",
                            ParkName = "Indiana Dunes National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 34,
                            Location = "Michigan",
                            ParkName = "Isle Royale National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 35,
                            Location = "California",
                            ParkName = "Joshua Tree National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 36,
                            Location = "Alaska",
                            ParkName = "Katmai National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 37,
                            Location = "Alaska",
                            ParkName = "Kenai Fjords National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 38,
                            Location = "California",
                            ParkName = "Kings Canyon National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 39,
                            Location = "Alaska",
                            ParkName = "Kobuk Valley National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 40,
                            Location = "Alaska",
                            ParkName = "Lake Clark National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 41,
                            Location = "California",
                            ParkName = "Lassen Volcanic Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 42,
                            Location = "Kentucky",
                            ParkName = "Mammoth Cave Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 43,
                            Location = "Colorado",
                            ParkName = "Mesa Verde National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 44,
                            Location = "Washington",
                            ParkName = "Mount Rainier National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 45,
                            Location = "Washington",
                            ParkName = "North Cascades National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 46,
                            Location = "Washington",
                            ParkName = "Olympic National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 47,
                            Location = "Arizona",
                            ParkName = "Petrified Forest National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 48,
                            Location = "California",
                            ParkName = "Pinnacles National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 49,
                            Location = "California",
                            ParkName = "Redwood National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 50,
                            Location = "Colorado",
                            ParkName = "Rocky Mountain National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 51,
                            Location = "Arizona",
                            ParkName = "Saguaro National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 52,
                            Location = "California",
                            ParkName = "Sequoia National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 53,
                            Location = "Virginia",
                            ParkName = "Shenandoah National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 54,
                            Location = "North Dakota",
                            ParkName = "Theodore Roosevelt National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 55,
                            Location = "U.S. Virgin Islands",
                            ParkName = "Virgin Islands National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 56,
                            Location = "Minnesota",
                            ParkName = "Voyageurs National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 57,
                            Location = "South Dakota",
                            ParkName = "Wind Cave National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 58,
                            Location = "Alaska",
                            ParkName = "Wrangell-St. Elias National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 59,
                            Location = "Wyoming",
                            ParkName = "Yellowstone National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 60,
                            Location = "California",
                            ParkName = "Yosemite National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 61,
                            Location = "Utah",
                            ParkName = "Zion National Park",
                            TypeOfPark = "National"
                        },
                        new
                        {
                            ParkId = 62,
                            Location = "Oregon",
                            ParkName = "Goose Lake State Recreation Area",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 63,
                            Location = "Oregon",
                            ParkName = "Frenchglen Hotel State Heritage Site",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 64,
                            Location = "Oregon",
                            ParkName = "Ontario State Recreation Site",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 65,
                            Location = "Oregon",
                            ParkName = "Farewell Bend State Recreation Area",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 66,
                            Location = "Oregon",
                            ParkName = "Kam Wah Chung State Heritage Site",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 67,
                            Location = "Oregon",
                            ParkName = "Unity Forest State Scenic Corridor",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 68,
                            Location = "Oregon",
                            ParkName = "Unity Lake State Recreation Site",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 69,
                            Location = "Oregon",
                            ParkName = "Clyde Holliday State Recreation Site",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 70,
                            Location = "Oregon",
                            ParkName = "Succor Creek State Natural Area",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 71,
                            Location = "Oregon",
                            ParkName = "Lake Owyhee State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 72,
                            Location = "Oregon",
                            ParkName = "Catherine Creek State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 73,
                            Location = "Oregon",
                            ParkName = "Hat Rock State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 74,
                            Location = "Oregon",
                            ParkName = "Hilgard Junction State Recreation Area",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 75,
                            Location = "Oregon",
                            ParkName = "Red Bridge State Wayside",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 76,
                            Location = "Oregon",
                            ParkName = "Ukiah & Dale Forest State Scenic Corridor",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 77,
                            Location = "Oregon",
                            ParkName = "Emigrant Springs State Heritage Area",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 78,
                            Location = "Oregon",
                            ParkName = "Wallowa Lake Highway Forest State Scenic Corridor",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 79,
                            Location = "Oregon",
                            ParkName = "Wallowa River Rest Area",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 80,
                            Location = "Oregon",
                            ParkName = "Minam State Recreation Area",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 81,
                            Location = "Oregon",
                            ParkName = "Wallowa Lake State Recreation Area",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 82,
                            Location = "Oregon",
                            ParkName = "Iwetemlaykin State Heritage Site",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 83,
                            Location = "Oregon",
                            ParkName = "Casey State Recreation Site,Recreation Site",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 84,
                            Location = "Oregon",
                            ParkName = "Prospect State Scenic Viewpoint",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 85,
                            Location = "Oregon",
                            ParkName = "Joseph H. Stewart State Recreation Area",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 86,
                            Location = "Oregon",
                            ParkName = "The Cove Palisades State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 87,
                            Location = "Oregon",
                            ParkName = "Jasper Point Campground",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 88,
                            Location = "Oregon",
                            ParkName = "Prineville Reservoir State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 89,
                            Location = "Oregon",
                            ParkName = "Heritage Landing (Deschutes)",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 90,
                            Location = "Oregon",
                            ParkName = "White River Falls State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 91,
                            Location = "Oregon",
                            ParkName = "Deschutes River State Recreation Area",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 92,
                            Location = "Oregon",
                            ParkName = "Cline Falls State Scenic Viewpoint",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 93,
                            Location = "Oregon",
                            ParkName = "Fort Rock State Natural Area",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 94,
                            Location = "Oregon",
                            ParkName = "La Pine State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 95,
                            Location = "Oregon",
                            ParkName = "Pilot Butte State Scenic Viewpoint",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 96,
                            Location = "Oregon",
                            ParkName = "Tumalo State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 97,
                            Location = "Oregon",
                            ParkName = "Smith Rock State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 98,
                            Location = "Oregon",
                            ParkName = "Booth State Scenic Corridor",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 99,
                            Location = "Oregon",
                            ParkName = "Humbug Mountain State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 100,
                            Location = "Oregon",
                            ParkName = "Port Orford Heads State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 101,
                            Location = "Oregon",
                            ParkName = "Cape Blanco State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 102,
                            Location = "Oregon",
                            ParkName = "Bullards Beach State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 103,
                            Location = "Oregon",
                            ParkName = "Alfred A. Loeb State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 104,
                            Location = "Oregon",
                            ParkName = "Elijah Bristow State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 105,
                            Location = "Oregon",
                            ParkName = "Cape Arago State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 106,
                            Location = "Oregon",
                            ParkName = "Shore Acres State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 107,
                            Location = "Oregon",
                            ParkName = "William M. Tugman State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 108,
                            Location = "Oregon",
                            ParkName = "Sunset Bay State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 109,
                            Location = "Oregon",
                            ParkName = "Illinois River Forks State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 110,
                            Location = "Oregon",
                            ParkName = "Molalla River State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 111,
                            Location = "Oregon",
                            ParkName = "Beaver Creek State Natural Area",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 112,
                            Location = "Oregon",
                            ParkName = "Umpqua Lighthouse State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 113,
                            Location = "Oregon",
                            ParkName = "Carl G. Washburne Memorial State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 114,
                            Location = "Oregon",
                            ParkName = "Jessie M. Honeyman Memorial State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 115,
                            Location = "Oregon",
                            ParkName = "Willamette Mission State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 116,
                            Location = "Oregon",
                            ParkName = "Milo McIver State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 117,
                            Location = "Oregon",
                            ParkName = "Ainsworth State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 118,
                            Location = "Oregon",
                            ParkName = "Guy W. Talbot State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 119,
                            Location = "Oregon",
                            ParkName = "Mayer State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 120,
                            Location = "Oregon",
                            ParkName = "Memaloose State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 121,
                            Location = "Oregon",
                            ParkName = "Starvation Creek State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 122,
                            Location = "Oregon",
                            ParkName = "Viento State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 123,
                            Location = "Oregon",
                            ParkName = "Rooster Rock State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 124,
                            Location = "Oregon",
                            ParkName = "Fort Stevens State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 125,
                            Location = "Oregon",
                            ParkName = "Bob Straub State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 126,
                            Location = "Oregon",
                            ParkName = "Ecola State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 127,
                            Location = "Oregon",
                            ParkName = "Oswald West State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 128,
                            Location = "Oregon",
                            ParkName = "Nehalem Bay State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 129,
                            Location = "Oregon",
                            ParkName = "Ona Beach State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 130,
                            Location = "Oregon",
                            ParkName = "South Beach State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 131,
                            Location = "Oregon",
                            ParkName = "Cascadia State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 132,
                            Location = "Oregon",
                            ParkName = "Silver Falls State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 133,
                            Location = "Oregon",
                            ParkName = "Beverly Beach State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 134,
                            Location = "Oregon",
                            ParkName = "Collier Memorial State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 135,
                            Location = "Oregon",
                            ParkName = "L. L. 'Stub' Stewart State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 136,
                            Location = "Oregon",
                            ParkName = "State Capitol State Park",
                            TypeOfPark = "State"
                        },
                        new
                        {
                            ParkId = 137,
                            Location = "Oregon",
                            ParkName = "Cottonwood Canyon State Park",
                            TypeOfPark = "State"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
