using Microsoft.EntityFrameworkCore;

namespace ParksAPI.Models
{
    public class ParksAPIContext : DbContext
    {
        public ParksAPIContext(DbContextOptions<ParksAPIContext> options)
            : base(options)
        {
        }

        public DbSet<Park> Parks { get; set; }

        protected override void OnModelCreating(ModelBuilder builder)
        {
        builder.Entity<Park>()
            .HasData(
                new Park { ParkId = 1, Name = "Acadia National Park", Type = "National", Location = "Maine" },
                new Park { ParkId = 2, Name = "American Samoa National Park	", Type = "National", Location = "American Samoa Territory" },
                new Park { ParkId = 3, Name = "Arches National Park	", Type = "National", Location = "Utah" },
                new Park { ParkId = 4, Name = "Badlands National Park ", Type = "National", Location = "South Dakota" },
                new Park { ParkId = 5, Name = "Big Bend National Park", Type = "National", Location = "Texas" },
                new Park { ParkId = 6, Name = "Biscayne National Park", Type = "National", Location = "Florida" },
                new Park { ParkId = 7, Name = "Black Canyon of the Gunnison National Park", Type = "National", Location = "Colorado" },
                new Park { ParkId = 8, Name = "Bryce Canyon National Park", Type = "National", Location = "Utah" },
                new Park { ParkId = 9, Name = "Canyonlands National Park", Type = "National", Location = "Utah" },
                new Park { ParkId = 10, Name = "Capitol Reef National Park", Type = "National", Location = "Utah" },
                new Park { ParkId = 11, Name = "Carlsbad Caverns National Park", Type = "National", Location = "New Mexico" },
                new Park { ParkId = 12, Name = "Channel Islands National Park", Type = "National", Location = "California" },
                new Park { ParkId = 13, Name = "Congaree National Park", Type = "National", Location = "South Carolina" },
                new Park { ParkId = 14, Name = "Crater Lake National Park", Type = "National", Location = "Oregon" },
                new Park { ParkId = 15, Name = "Cuyahoga Valley National Park", Type = "National", Location = "Ohio" },
                new Park { ParkId = 16, Name = "Death Valley National Park", Type = "National", Location = "California and Nevada" },
                new Park { ParkId = 17, Name = "Denali National Park", Type = "National", Location = "Alaska" },
                new Park { ParkId = 18, Name = "Dry Tortugas National Park", Type = "National", Location = "Florida" },
                new Park { ParkId = 19, Name = "Everglades National Park", Type = "National", Location = "Florida" },
                new Park { ParkId = 20, Name = "Gates of the Arctic National Park", Type = "National", Location = "Alaska" },
                new Park { ParkId = 21, Name = "Gateway Arch National Park", Type = "National", Location = "Missouri" },
                new Park { ParkId = 22, Name = "Glacier National Park", Type = "National", Location = "Montana" },
                new Park { ParkId = 23, Name = "Glacier Bay National Park", Type = "National", Location = "Alaska" },
                new Park { ParkId = 24, Name = "Grand Canyon National Park", Type = "National", Location = "Arizona" },
                new Park { ParkId = 25, Name = "Grand Teton National Park", Type = "National", Location = "Wyoming" },
                new Park { ParkId = 26, Name = "Great Basin National Park", Type = "National", Location = "Nevada" },
                new Park { ParkId = 27, Name = "Great Sand Dunes National Park", Type = "National", Location = "Colorado" },
                new Park { ParkId = 28, Name = "Great Smoky Mountains National Park", Type = "National", Location = "North Carolina and Tennessee" },
                new Park { ParkId = 29, Name = "Guadalupe Mountains National Park", Type = "National", Location = "Texas" },
                new Park { ParkId = 30, Name = "Haleakala National Park", Type = "National", Location = "Hawaii" },
                new Park { ParkId = 31, Name = "Hawaii Volcanoes National Park", Type = "National", Location = "Hawaii" },
                new Park { ParkId = 32, Name = "Hot Springs National Park", Type = "National", Location = "Arkansas" },
                new Park { ParkId = 33, Name = "Indiana Dunes National Park", Type = "National", Location = "Indiana" },
                new Park { ParkId = 34, Name = "Isle Royale National Park", Type = "National", Location = "Michigan" },
                new Park { ParkId = 35, Name = "Joshua Tree National Park", Type = "National", Location = "California" },
                new Park { ParkId = 36, Name = "Katmai National Park", Type = "National", Location = "Alaska" },
                new Park { ParkId = 37, Name = "Kenai Fjords National Park", Type = "National", Location = "Alaska" },
                new Park { ParkId = 38, Name = "Kings Canyon National Park", Type = "National", Location = "California" },
                new Park { ParkId = 39, Name = "Kobuk Valley National Park", Type = "National", Location = "Alaska" },
                new Park { ParkId = 40, Name = "Lake Clark National Park", Type = "National", Location = "Alaska" },
                new Park { ParkId = 41, Name = "Lassen Volcanic Park", Type = "National", Location = "California" },
                new Park { ParkId = 42, Name = "Mammoth Cave Park", Type = "National", Location = "Kentucky" },
                new Park { ParkId = 43, Name = "Mesa Verde National Park", Type = "National", Location = "Colorado" },
                new Park { ParkId = 44, Name = "Mount Rainier National Park", Type = "National", Location = "Washington" },
                new Park { ParkId = 45, Name = "North Cascades National Park", Type = "National", Location = "Washington" },
                new Park { ParkId = 46, Name = "Olympic National Park", Type = "National", Location = "Washington" },
                new Park { ParkId = 47, Name = "Petrified Forest National Park", Type = "National", Location = "Arizona" },
                new Park { ParkId = 48, Name = "Pinnacles National Park", Type = "National", Location = "California" },
                new Park { ParkId = 49, Name = "Redwood National Park", Type = "National", Location = "California" },
                new Park { ParkId = 50, Name = "Rocky Mountain National Park", Type = "National", Location = "Colorado" },
                new Park { ParkId = 51, Name = "Saguaro National Park", Type = "National", Location = "Arizona" },
                new Park { ParkId = 52, Name = "Sequoia National Park", Type = "National", Location = "California" },
                new Park { ParkId = 53, Name = "Shenandoah National Park", Type = "National", Location = "Virginia" },
                new Park { ParkId = 54, Name = "Theodore Roosevelt National Park", Type = "National", Location = "North Dakota" },
                new Park { ParkId = 55, Name = "Virgin Islands National Park", Type = "National", Location = "U.S. Virgin Islands" },
                new Park { ParkId = 56, Name = "Voyageurs National Park", Type = "National", Location = "Minnesota" },
                new Park { ParkId = 57, Name = "Wind Cave National Park", Type = "National", Location = "South Dakota" },
                new Park { ParkId = 58, Name = "Wrangell-St. Elias National Park", Type = "National", Location = "Alaska" },
                new Park { ParkId = 59, Name = "Yellowstone National Park", Type = "National", Location = "Wyoming" },
                new Park { ParkId = 60, Name = "Yosemite National Park", Type = "National", Location = "California" },
                new Park { ParkId = 61, Name = "Zion National Park", Type = "National", Location = "Utah" },
                new Park { ParkId = 62, Name = "Goose Lake State Recreation Area", Type = "State", Location = "Oregon" },
                new Park { ParkId = 63, Name = "Frenchglen Hotel State Heritage Site", Type = "State", Location = "Oregon" },
                new Park { ParkId = 64, Name = "Ontario State Recreation Site", Type = "State", Location = "Oregon" },
                new Park { ParkId = 65, Name = "Farewell Bend State Recreation Area", Type = "State", Location = "Oregon" },
                new Park { ParkId = 66, Name = "Kam Wah Chung State Heritage Site", Type = "State", Location = "Oregon" },
                new Park { ParkId = 67, Name = "Unity Forest State Scenic Corridor", Type = "State", Location = "Oregon" },
                new Park { ParkId = 68, Name = "Unity Lake State Recreation Site", Type = "State", Location = "Oregon" },
                new Park { ParkId = 69, Name = "Clyde Holliday State Recreation Site", Type = "State", Location = "Oregon" },
                new Park { ParkId = 70, Name = "Succor Creek State Natural Area", Type = "State", Location = "Oregon" },
                new Park { ParkId = 71, Name = "Lake Owyhee State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 72, Name = "Catherine Creek State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 73, Name = "Hat Rock State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 74, Name = "Hilgard Junction State Recreation Area", Type = "State", Location = "Oregon" },
                new Park { ParkId = 75, Name = "Red Bridge State Wayside", Type = "State", Location = "Oregon" },
                new Park { ParkId = 76, Name = "Ukiah & Dale Forest State Scenic Corridor", Type = "State", Location = "Oregon" },
                new Park { ParkId = 77, Name = "Emigrant Springs State Heritage Area", Type = "State", Location = "Oregon" },
                new Park { ParkId = 78, Name = "Wallowa Lake Highway Forest State Scenic Corridor", Type = "State", Location = "Oregon" },
                new Park { ParkId = 79, Name = "Wallowa River Rest Area", Type = "State", Location = "Oregon" },
                new Park { ParkId = 80, Name = "Minam State Recreation Area", Type = "State", Location = "Oregon" },
                new Park { ParkId = 81, Name = "Wallowa Lake State Recreation Area", Type = "State", Location = "Oregon" },
                new Park { ParkId = 82, Name = "Iwetemlaykin State Heritage Site", Type = "State", Location = "Oregon" },
                new Park { ParkId = 83, Name = "Casey State Recreation Site,Recreation Site", Type = "State", Location = "Oregon" },
                new Park { ParkId = 84, Name = "Prospect State Scenic Viewpoint", Type = "State", Location = "Oregon" },
                new Park { ParkId = 85, Name = "Joseph H. Stewart State Recreation Area", Type = "State", Location = "Oregon" },
                new Park { ParkId = 86, Name = "The Cove Palisades State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 87, Name = "Jasper Point Campground", Type = "State", Location = "Oregon" },
                new Park { ParkId = 88, Name = "Prineville Reservoir State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 89, Name = "Heritage Landing (Deschutes)", Type = "State", Location = "Oregon" },
                new Park { ParkId = 90, Name = "White River Falls State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 91, Name = "Deschutes River State Recreation Area", Type = "State", Location = "Oregon" },
                new Park { ParkId = 92, Name = "Cline Falls State Scenic Viewpoint", Type = "State", Location = "Oregon" },
                new Park { ParkId = 93, Name = "Fort Rock State Natural Area", Type = "State", Location = "Oregon" },
                new Park { ParkId = 94, Name = "La Pine State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 95, Name = "Pilot Butte State Scenic Viewpoint", Type = "State", Location = "Oregon" },
                new Park { ParkId = 96, Name = "Tumalo State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 97, Name = "Smith Rock State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 98, Name = "Booth State Scenic Corridor", Type = "State", Location = "Oregon" },
                new Park { ParkId = 99, Name = "Humbug Mountain State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 100, Name = "Port Orford Heads State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 101, Name = "Cape Blanco State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 102, Name = "Bullards Beach State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 103, Name = "Alfred A. Loeb State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 104, Name = "Elijah Bristow State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 105, Name = "Cape Arago State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 106, Name = "Shore Acres State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 107, Name = "William M. Tugman State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 108, Name = "Sunset Bay State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 109, Name = "Illinois River Forks State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 110, Name = "Molalla River State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 111, Name = "Beaver Creek State Natural Area", Type = "State", Location = "Oregon" },
                new Park { ParkId = 112, Name = "Umpqua Lighthouse State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 113, Name = "Carl G. Washburne Memorial State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 114, Name = "Jessie M. Honeyman Memorial State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 115, Name = "Willamette Mission State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 116, Name = "Milo McIver State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 117, Name = "Ainsworth State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 118, Name = "Guy W. Talbot State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 119, Name = "Mayer State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 120, Name = "Memaloose State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 121, Name = "Starvation Creek State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 122, Name = "Viento State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 123, Name = "Rooster Rock State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 124, Name = "Fort Stevens State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 125, Name = "Bob Straub State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 126, Name = "Ecola State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 127, Name = "Oswald West State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 128, Name = "Nehalem Bay State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 129, Name = "Ona Beach State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 130, Name = "South Beach State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 131, Name = "Cascadia State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 132, Name = "Silver Falls State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 133, Name = "Beverly Beach State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 134, Name = "Collier Memorial State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 135, Name = "L. L. 'Stub' Stewart State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 136, Name = "State Capitol State Park", Type = "State", Location = "Oregon" },
                new Park { ParkId = 137, Name = "Cottonwood Canyon State Park", Type = "State", Location = "Oregon" }                
            );
        }
    }
}